// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rpg_console.Context;

#nullable disable

namespace rpg_console.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230501062539_moedas")]
    partial class moedas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("rpg_console.Models.EquipamentoArma", b =>
                {
                    b.Property<int>("EquipamentoArmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Defesa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("EquipamentoArmaId");

                    b.ToTable("Arma");
                });

            modelBuilder.Entity("rpg_console.Models.EquipamentoArmadura", b =>
                {
                    b.Property<int>("EquipamentoArmaduraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ataque")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("EquipamentoArmaduraId");

                    b.ToTable("Armadura");
                });

            modelBuilder.Entity("rpg_console.Models.Inimigo", b =>
                {
                    b.Property<int>("InimigoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Defesa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Experiencia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Forca")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Moedas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("InimigoId");

                    b.ToTable("Inimigos");
                });

            modelBuilder.Entity("rpg_console.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<int?>("JogadorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.HasIndex("JogadorId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("rpg_console.Models.Jogador", b =>
                {
                    b.Property<int>("JogadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArmaEquipamentoArmaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArmaduraEquipamentoArmaduraId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Defesa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Experiencia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Forca")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Moedas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("JogadorId");

                    b.HasIndex("ArmaEquipamentoArmaId");

                    b.HasIndex("ArmaduraEquipamentoArmaduraId");

                    b.ToTable("Jogadores");
                });

            modelBuilder.Entity("rpg_console.Models.Item", b =>
                {
                    b.HasOne("rpg_console.Models.Jogador", null)
                        .WithMany("Itens")
                        .HasForeignKey("JogadorId");
                });

            modelBuilder.Entity("rpg_console.Models.Jogador", b =>
                {
                    b.HasOne("rpg_console.Models.EquipamentoArma", "Arma")
                        .WithMany()
                        .HasForeignKey("ArmaEquipamentoArmaId");

                    b.HasOne("rpg_console.Models.EquipamentoArmadura", "Armadura")
                        .WithMany()
                        .HasForeignKey("ArmaduraEquipamentoArmaduraId");

                    b.Navigation("Arma");

                    b.Navigation("Armadura");
                });

            modelBuilder.Entity("rpg_console.Models.Jogador", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
